name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '4.27.0'
          environment: production
          secrets: |
            HMAC_SECRET
            KEY_DERIVATION_SECRET
        env:
          HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
          KEY_DERIVATION_SECRET: ${{ secrets.KEY_DERIVATION_SECRET }}
